global:
  scrape_interval: 30s
  scrape_timeout: 10s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager-1:9093
      - alertmanager-2:9093

rule_files:
- rules.yml

scrape_configs:
- job_name: prometheus
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - prometheus-1:9090
    - prometheus-2:9090
    - alertmanager-1:9093
    - alertmanager-2:9093
