global:
  scrape_interval: 30s
  scrape_timeout: 10s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 127.0.0.1:9093
      - 127.0.0.1:9094

rule_files:
- rules.yml

scrape_configs:
- job_name: prometheus
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 127.0.0.1:9090
    - 127.0.0.1:9091
    - 127.0.0.1:9093
    - 127.0.0.1:9093
- job_name: node_exporter
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 127.0.0.1:9100
