global:
  resolve_timeout: 5m

route:
  group_by: [job]
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 5m
  receiver: 'web.hook'
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:8080/'
