global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 30s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 127.0.0.1:9093
    api_version: v2

rule_files:
- rules.yml

scrape_configs:
- job_name: prometheus
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 127.0.0.1:9090
    - 127.0.0.1:9093
- job_name: node_exporter
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - 127.0.0.1:9100
- job_name: file_sd
  file_sd_configs:
  - files:
    - targets/*.yml
